name: Docker Image Sandbox

on:
  push:
    branches: 
        - master

jobs:
  dev-build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository }}:latest
    
    # Deploy on Remote Server
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              docker rmi ghcr.io/akatsukione/react-vite-pipeline-template:latest
              docker pull ghcr.io/akatsukione/react-vite-pipeline-template:latest
              docker run -p 5000:5173 --network=host ${{ github.repository }}:latest


          
      

