name: Docker Image Sandbox

on:
  push:
    branches: 
        - master

jobs:
  dev-build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    #   - name: Inspect github.repository
    #     run: echo "${{github.repository}}"

    #   - name: Build the Docker image
    #     run: |
    #       docker build -t ${{ github.repository }}:${{ github.sha }} .
        #   docker tag ${{ github.repository }}:${{ github.sha }}
      
      - name: Push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
      # - name: Push Docker image to GHCR
      #   # uses: docker/build-push-action@v4
      #   run: |
      #       docker build -t ghcr.io/akatsukione/react-vite-pipeline-template:${{ github.sha }} .
      #       docker push ghcr.io/akatsukione/react-vite-pipeline-template:${{ github.sha }}
    
    # Deploy on DEV
      - name: SSH access
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            #key: ${{ secrets.SSH_KEY }}
            #port: ${{ secrets.SSH_PORT }}

      - name: Run the Docker image
        run: docker pull ghcr.io/akatuskione/react-vite-pipeline-template:${{ github.sha }}
            # docker images
    # #         docker run -p 5000:5173 --network=host ${{ github.actor }}/${{ github.repository }}:latest


          
      

