name: Docker Image Sandbox

on:
  push:
    branches: 
        - master

jobs:
  dev-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ${{ secrets.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ github.repository }}:${{ github.sha }} .
        #   docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest
      
      - name: Push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
            context: .
            push: true
            tags: |
                ${{ secrets.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
    
    # Deploy on DEV
    #   - name: SSH and build docker
    #     uses: appleboy/ssh-action@master
    #     with:
    #         host: ${{ secrets.SSH_HOST }}
    #         username: ${{ secrets.SSH_USERNAME }}
    #         password: ${{ secrets.SSH_PASSWORD }}
    #         #key: ${{ secrets.SSH_KEY }}
    #         #port: ${{ secrets.SSH_PORT }}

    #   - name: Run the Docker image
    #     run: |
    #         docker pull ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
    #         docker run -p 5000:5173 --network=host ${{ github.actor }}/${{ github.repository }}:latest


          
      

